In [6]:
import pandas as pd
import pipeline_utilities as p_util

In [11]:
# Create a list of DataFrames by using a list comprehension with read_csv
days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday']
dfs = [pd.read_csv(f'https://static.bc-edx.com/ai/ail-v-1-0/m12/lesson_3/datasets/garments-worker-productivity-{day}.csv') for day in days]
dfs[-1].head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/3/2015,Quarter1,finishing,Saturday,4,0.80,4.15,NaN,6600,0,0.0,0,0,20.0,0.988025
1,1/3/2015,Quarter1,finishing,Saturday,11,0.75,2.90,NaN,5640,0,0.0,0,0,17.0,0.987880
2,1/3/2015,Quarter1,finishing,Saturday,9,0.80,4.15,NaN,960,0,0.0,0,0,8.0,0.956271
3,1/3/2015,Quarter1,finishing,Saturday,3,0.75,3.94,NaN,1560,0,0.0,0,0,8.0,0.945278
4,1/3/2015,Quarter1,finishing,Saturday,1,0.80,3.94,NaN,960,0,0.0,0,0,8.0,0.902917

In [16]:
# Create a dictionary with the models
model_dict = {}
for df in dfs:
    print(df.iloc[0,3])
    model_dict[f"{df.iloc[0,3]}_model"] = p_util.prod_model_generator(df)
    print("----------")

Sunday
Mean Squared Error: 0.0055386373203709476
R-squared: 0.7420392602900376
Adjusted R-squared: 0.7324851588192982
----------
Monday
Mean Squared Error: 0.0036349025620036383
R-squared: 0.7976822311879014
Adjusted R-squared: 0.790188980491157
----------
Tuesday
Mean Squared Error: 0.004918303710778881
R-squared: 0.786741066080846
Adjusted R-squared: 0.7791246755837333
----------
Wednesday
Mean Squared Error: 0.007210243229209076
R-squared: 0.4794673467831152
Adjusted R-squared: 0.46087689488251216
----------
Thursday
Mean Squared Error: 0.005796475165416865
R-squared: 0.773599971836475
Adjusted R-squared: 0.7655142565449206
----------
Saturday
Mean Squared Error: 0.004739969509536248
R-squared: 0.7753589866592869
Adjusted R-squared: 0.7659989444367572
----------

In [13]:
model_dict= {}

AttributeError: 'list' object has no attribute 'info'